from dataclasses import dataclass, field
from typing import Optional

@dataclass
class IRSDKVars:
    AirDensity: Optional[float] = field(default=None, metadata={"desc": "Density of air at start/finish line, kg/m^3"})
    AirPressure: Optional[float] = field(default=None, metadata={"desc": "Pressure of air at start/finish line, Pa"})
    AirTemp: Optional[float] = field(default=None, metadata={"desc": "Temperature of air at start/finish line, C"})
    Brake: Optional[float] = field(default=None, metadata={"desc": "0=brake released to 1=max pedal force, %"})
    BrakeABSactive: Optional[bool] = field(default=None, metadata={"desc": "true if abs is currently reducing brake force pressure"})
    BrakeRaw: Optional[float] = field(default=None, metadata={"desc": "Raw brake input 0=brake released to 1=max pedal force, %"})
    CamCameraNumber: Optional[int] = field(default=None, metadata={"desc": "Active camera number"})
    CamCameraState: Optional[int] = field(default=None, metadata={"desc": "State of camera system, irsdk_CameraState"})
    CamCarIdx: Optional[int] = field(default=None, metadata={"desc": "Active camera's focus car index"})
    CamGroupNumber: Optional[int] = field(default=None, metadata={"desc": "Active camera group number"})
    CarDistAhead: Optional[float] = field(default=None, metadata={"desc": "Distance to first car in front of player in meters, m"})
    CarDistBehind: Optional[float] = field(default=None, metadata={"desc": "Distance to first car behind player in meters, m"})
    CarIdxBestLapNum: Optional[int] = field(default=None, metadata={"desc": "Cars best lap number"})
    CarIdxBestLapTime: Optional[float] = field(default=None, metadata={"desc": "Cars best lap time, s"})
    CarIdxClass: Optional[int] = field(default=None, metadata={"desc": "Cars class id by car index"})
    CarIdxClassPosition: Optional[int] = field(default=None, metadata={"desc": "Cars class position in race by car index"})
    CarIdxEstTime: Optional[float] = field(default=None, metadata={"desc": "Estimated time to reach current location on track, s"})
    CarIdxF2Time: Optional[float] = field(default=None, metadata={"desc": "Race time behind leader or fastest lap time otherwise, s"})
    CarIdxFastRepairsUsed: Optional[int] = field(default=None, metadata={"desc": "How many fast repairs each car has used"})
    CarIdxGear: Optional[int] = field(default=None, metadata={"desc": "-1=reverse  0=neutral  1..n=current gear by car index"})
    CarIdxLap: Optional[int] = field(default=None, metadata={"desc": "Laps started by car index"})
    CarIdxLapCompleted: Optional[int] = field(default=None, metadata={"desc": "Laps completed by car index"})
    CarIdxLapDistPct: Optional[float] = field(default=None, metadata={"desc": "Percentage distance around lap by car index, %"})
    CarIdxLastLapTime: Optional[float] = field(default=None, metadata={"desc": "Cars last lap time, s"})
    CarIdxOnPitRoad: Optional[bool] = field(default=None, metadata={"desc": "On pit road between the cones by car index"})
    CarIdxP2P_Count: Optional[int] = field(default=None, metadata={"desc": "Push2Pass count of usage (or remaining in Race)"})
    CarIdxP2P_Status: Optional[bool] = field(default=None, metadata={"desc": "Push2Pass active or not"})
    CarIdxPaceFlags: Optional[int] = field(default=None, metadata={"desc": "Pacing status flags for each car, irsdk_PaceFlags"})
    CarIdxPaceLine: Optional[int] = field(default=None, metadata={"desc": "What line cars are pacing in  or -1 if not pacing"})
    CarIdxPaceRow: Optional[int] = field(default=None, metadata={"desc": "What row cars are pacing in  or -1 if not pacing"})
    CarIdxPosition: Optional[int] = field(default=None, metadata={"desc": "Cars position in race by car index"})
    CarIdxQualTireCompound: Optional[str] = field(default=None, metadata={"desc": "Cars Qual tire compound"})
    CarIdxQualTireCompoundLocked: Optional[bool] = field(default=None, metadata={"desc": "Cars Qual tire compound is locked-in"})
    CarIdxRPM: Optional[float] = field(default=None, metadata={"desc": "Engine rpm by car index, revs/min"})
    CarIdxSessionFlags: Optional[int] = field(default=None, metadata={"desc": "Session flags for each player, irsdk_Flags"})
    CarIdxSteer: Optional[float] = field(default=None, metadata={"desc": "Steering wheel angle by car index, rad"})
    CarIdxTireCompound: Optional[str] = field(default=None, metadata={"desc": "Cars current tire compound"})
    CarIdxTrackSurface: Optional[int] = field(default=None, metadata={"desc": "Track surface type by car index, irsdk_TrkLoc"})
    CarIdxTrackSurfaceMaterial: Optional[int] = field(default=None, metadata={"desc": "Track surface material type by car index, irsdk_TrkSurf"})
    CarLeftRight: Optional[int] = field(default=None, metadata={"desc": "Notify if car is to the left or right of driver, irsdk_CarLeftRight"})
    ChanAvgLatency: Optional[float] = field(default=None, metadata={"desc": "Communications average latency, s"})
    ChanClockSkew: Optional[float] = field(default=None, metadata={"desc": "Communications server clock skew, s"})
    ChanLatency: Optional[float] = field(default=None, metadata={"desc": "Communications latency, s"})
    ChanPartnerQuality: Optional[float] = field(default=None, metadata={"desc": "Partner communications quality, %"})
    ChanQuality: Optional[float] = field(default=None, metadata={"desc": "Communications quality, %"})
    Clutch: Optional[float] = field(default=None, metadata={"desc": "0=disengaged to 1=fully engaged, %"})
    ClutchRaw: Optional[float] = field(default=None, metadata={"desc": "Raw clutch input 0=disengaged to 1=fully engaged, %"})
    CpuUsageBG: Optional[float] = field(default=None, metadata={"desc": "Percent of available tim bg thread took with a 1 sec avg, %"})
    CpuUsageFG: Optional[float] = field(default=None, metadata={"desc": "Percent of available tim fg thread took with a 1 sec avg, %"})
    DCDriversSoFar: Optional[int] = field(default=None, metadata={"desc": "Number of team drivers who have run a stint"})
    DCLapStatus: Optional[int] = field(default=None, metadata={"desc": "Status of driver change lap requirements"})
    dcPitSpeedLimiterToggle: Optional[bool] = field(default=None, metadata={"desc": "In car traction control active"})
    dcStarter: Optional[bool] = field(default=None, metadata={"desc": "In car trigger car starter"})
    dcToggleWindshieldWipers: Optional[bool] = field(default=None, metadata={"desc": "In car turn wipers on or off"})
    dcTriggerWindshieldWipers: Optional[bool] = field(default=None, metadata={"desc": "In car momentarily turn on wipers"})
    DisplayUnits: Optional[int] = field(default=None, metadata={"desc": "Default units for the user interface 0 = english 1 = metric"})
    dpFastRepair: Optional[bool] = field(default=None, metadata={"desc": "Pitstop fast repair set"})
    dpFuelAddKg: Optional[float] = field(default=None, metadata={"desc": "Pitstop fuel add amount, kg"})
    dpFuelAutoFillActive: Optional[bool] = field(default=None, metadata={"desc": "Pitstop auto fill fuel next stop flag"})
    dpFuelAutoFillEnabled: Optional[bool] = field(default=None, metadata={"desc": "Pitstop auto fill fuel system enabled"})
    dpFuelFill: Optional[bool] = field(default=None, metadata={"desc": "Pitstop fuel fill flag"})
    dpLFTireChange: Optional[bool] = field(default=None, metadata={"desc": "Pitstop lf tire change request"})
    dpLFTireColdPress: Optional[float] = field(default=None, metadata={"desc": "Pitstop lf tire cold pressure adjustment, Pa"})
    dpLRTireChange: Optional[bool] = field(default=None, metadata={"desc": "Pitstop lr tire change request"})
    dpLRTireColdPress: Optional[float] = field(default=None, metadata={"desc": "Pitstop lr tire cold pressure adjustment, Pa"})
    dpRFTireChange: Optional[bool] = field(default=None, metadata={"desc": "Pitstop rf tire change request"})
    dpRFTireColdPress: Optional[float] = field(default=None, metadata={"desc": "Pitstop rf cold tire pressure adjustment, Pa"})
    dpRRTireChange: Optional[bool] = field(default=None, metadata={"desc": "Pitstop rr tire change request"})
    dpRRTireColdPress: Optional[float] = field(default=None, metadata={"desc": "Pitstop rr tire cold pressure adjustment, Pa"})
    dpWindshieldTearoff: Optional[bool] = field(default=None, metadata={"desc": "Pitstop windshield tearoff"})
    DriverMarker: Optional[bool] = field(default=None, metadata={"desc": "Driver activated flag"})
    Engine0_RPM: Optional[float] = field(default=None, metadata={"desc": "Engine0Engine rpm, revs/min"})
    EngineWarnings: Optional[int] = field(default=None, metadata={"desc": "Bitfield for warning lights, irsdk_EngineWarnings"})
    EnterExitReset: Optional[int] = field(default=None, metadata={"desc": "Indicate action the reset key will take 0 enter 1 exit 2 reset"})
    FastRepairAvailable: Optional[int] = field(default=None, metadata={"desc": "How many fast repairs left  255 is unlimited"})
    FastRepairUsed: Optional[int] = field(default=None, metadata={"desc": "How many fast repairs used so far"})
    FogLevel: Optional[float] = field(default=None, metadata={"desc": "Fog level at start/finish line, %"})
    FrameRate: Optional[float] = field(default=None, metadata={"desc": "Average frames per second, fps"})
    FrontTireSetsAvailable: Optional[int] = field(default=None, metadata={"desc": "How many front tire sets are remaining  255 is unlimited"})
    FrontTireSetsUsed: Optional[int] = field(default=None, metadata={"desc": "How many front tire sets used so far"})
    FuelLevel: Optional[float] = field(default=None, metadata={"desc": "Liters of fuel remaining, l"})
    FuelLevelPct: Optional[float] = field(default=None, metadata={"desc": "Percent fuel remaining, %"})
    FuelPress: Optional[float] = field(default=None, metadata={"desc": "Engine fuel pressure, bar"})
    FuelUsePerHour: Optional[float] = field(default=None, metadata={"desc": "Engine fuel used instantaneous, kg/h"})
    Gear: Optional[int] = field(default=None, metadata={"desc": "-1=reverse  0=neutral  1..n=current gear"})
    GpuUsage: Optional[float] = field(default=None, metadata={"desc": "Percent of available tim gpu took with a 1 sec avg, %"})
    HandbrakeRaw: Optional[float] = field(default=None, metadata={"desc": "Raw handbrake input 0=handbrake released to 1=max force, %"})
    IsDiskLoggingActive: Optional[bool] = field(default=None, metadata={"desc": "0=disk based telemetry file not being written  1=being written"})
    IsDiskLoggingEnabled: Optional[bool] = field(default=None, metadata={"desc": "0=disk based telemetry turned off  1=turned on"})
    IsGarageVisible: Optional[bool] = field(default=None, metadata={"desc": "1=Garage screen is visible"})
    IsInGarage: Optional[bool] = field(default=None, metadata={"desc": "1=Car in garage physics running"})
    IsOnTrack: Optional[bool] = field(default=None, metadata={"desc": "1=Car on track physics running with player in car"})
    IsOnTrackCar: Optional[bool] = field(default=None, metadata={"desc": "1=Car on track physics running"})
    IsReplayPlaying: Optional[bool] = field(default=None, metadata={"desc": "0=replay not playing  1=replay playing"})
    Lap: Optional[int] = field(default=None, metadata={"desc": "Laps started count"})
    LapBestLap: Optional[int] = field(default=None, metadata={"desc": "Players best lap number"})
    LapBestLapTime: Optional[float] = field(default=None, metadata={"desc": "Players best lap time, s"})
    LapBestNLapLap: Optional[int] = field(default=None, metadata={"desc": "Player last lap in best N average lap time"})
    LapBestNLapTime: Optional[float] = field(default=None, metadata={"desc": "Player best N average lap time, s"})
    LapCompleted: Optional[int] = field(default=None, metadata={"desc": "Laps completed count"})
    LapCurrentLapTime: Optional[float] = field(default=None, metadata={"desc": "Estimate of players current lap time as shown in F3 box, s"})
    LapDeltaToBestLap: Optional[float] = field(default=None, metadata={"desc": "Delta time for best lap, s"})
    LapDeltaToBestLap_DD: Optional[float] = field(default=None, metadata={"desc": "Rate of change of delta time for best lap, s/s"})
    LapDeltaToBestLap_OK: Optional[bool] = field(default=None, metadata={"desc": "Delta time for best lap is valid"})
    LapDeltaToOptimalLap: Optional[float] = field(default=None, metadata={"desc": "Delta time for optimal lap, s"})
    LapDeltaToOptimalLap_DD: Optional[float] = field(default=None, metadata={"desc": "Rate of change of delta time for optimal lap, s/s"})
    LapDeltaToOptimalLap_OK: Optional[bool] = field(default=None, metadata={"desc": "Delta time for optimal lap is valid"})
    LapDeltaToSessionBestLap: Optional[float] = field(default=None, metadata={"desc": "Delta time for session best lap, s"})
    LapDeltaToSessionBestLap_DD: Optional[float] = field(default=None, metadata={"desc": "Rate of change of delta time for session best lap, s/s"})
    LapDeltaToSessionBestLap_OK: Optional[bool] = field(default=None, metadata={"desc": "Delta time for session best lap is valid"})
    LapDeltaToSessionLastlLap: Optional[float] = field(default=None, metadata={"desc": "Delta time for session last lap, s"})
    LapDeltaToSessionLastlLap_DD: Optional[float] = field(default=None, metadata={"desc": "Rate of change of delta time for session last lap, s/s"})
    LapDeltaToSessionLastlLap_OK: Optional[bool] = field(default=None, metadata={"desc": "Delta time for session last lap is valid"})
    LapDeltaToSessionOptimalLap: Optional[float] = field(default=None, metadata={"desc": "Delta time for session optimal lap, s"})
    LapDeltaToSessionOptimalLap_DD: Optional[float] = field(default=None, metadata={"desc": "Rate of change of delta time for session optimal lap, s/s"})
    LapDeltaToSessionOptimalLap_OK: Optional[bool] = field(default=None, metadata={"desc": "Delta time for session optimal lap is valid"})
    LapDist: Optional[float] = field(default=None, metadata={"desc": "Meters traveled from S/F this lap, m"})
    LapDistPct: Optional[float] = field(default=None, metadata={"desc": "Percentage distance around lap, %"})
    LapLasNLapSeq: Optional[int] = field(default=None, metadata={"desc": "Player num consecutive clean laps completed for N average"})
    LapLastLapTime: Optional[float] = field(default=None, metadata={"desc": "Players last lap time, s"})
    LapLastNLapTime: Optional[float] = field(default=None, metadata={"desc": "Player last N average lap time, s"})
    LatAccel: Optional[float] = field(default=None, metadata={"desc": "Lateral acceleration (including gravity), m/s^2"})
    LatAccel_ST: Optional[float] = field(default=None, metadata={"desc": "Lateral acceleration (including gravity) at 360 Hz, m/s^2"})
    LeftTireSetsAvailable: Optional[int] = field(default=None, metadata={"desc": "How many left tire sets are remaining  255 is unlimited"})
    LeftTireSetsUsed: Optional[int] = field(default=None, metadata={"desc": "How many left tire sets used so far"})
    LFbrakeLinePress: Optional[float] = field(default=None, metadata={"desc": "LF brake line pressure, bar"})
    LFcoldPressure: Optional[float] = field(default=None, metadata={"desc": "LF tire cold pressure  as set in the garage, kPa"})
    LFshockDefl: Optional[float] = field(default=None, metadata={"desc": "LF shock deflection, m"})
    LFshockDefl_ST: Optional[float] = field(default=None, metadata={"desc": "LF shock deflection at 360 Hz, m"})
    LFshockVel: Optional[float] = field(default=None, metadata={"desc": "LF shock velocity, m/s"})
    LFshockVel_ST: Optional[float] = field(default=None, metadata={"desc": "LF shock velocity at 360 Hz, m/s"})
    LFtempCL: Optional[float] = field(default=None, metadata={"desc": "LF tire left carcass temperature, C"})
    LFtempCM: Optional[float] = field(default=None, metadata={"desc": "LF tire middle carcass temperature, C"})
    LFtempCR: Optional[float] = field(default=None, metadata={"desc": "LF tire right carcass temperature, C"})
    LFTiresAvailable: Optional[int] = field(default=None, metadata={"desc": "How many left front tires are remaining  255 is unlimited"})
    LFTiresUsed: Optional[int] = field(default=None, metadata={"desc": "How many left front tires used so far"})
    LFwearL: Optional[float] = field(default=None, metadata={"desc": "LF tire left percent tread remaining, %"})
    LFwearM: Optional[float] = field(default=None, metadata={"desc": "LF tire middle percent tread remaining, %"})
    LFwearR: Optional[float] = field(default=None, metadata={"desc": "LF tire right percent tread remaining, %"})
    LoadNumTextures: Optional[bool] = field(default=None, metadata={"desc": "True if the car_num texture will be loaded"})
    LongAccel: Optional[float] = field(default=None, metadata={"desc": "Longitudinal acceleration (including gravity), m/s^2"})
    LongAccel_ST: Optional[float] = field(default=None, metadata={"desc": "Longitudinal acceleration (including gravity) at 360 Hz, m/s^2"})
    LRbrakeLinePress: Optional[float] = field(default=None, metadata={"desc": "LR brake line pressure, bar"})
    LRcoldPressure: Optional[float] = field(default=None, metadata={"desc": "LR tire cold pressure  as set in the garage, kPa"})
    LRshockDefl: Optional[float] = field(default=None, metadata={"desc": "LR shock deflection, m"})
    LRshockDefl_ST: Optional[float] = field(default=None, metadata={"desc": "LR shock deflection at 360 Hz, m"})
    LRshockVel: Optional[float] = field(default=None, metadata={"desc": "LR shock velocity, m/s"})
    LRshockVel_ST: Optional[float] = field(default=None, metadata={"desc": "LR shock velocity at 360 Hz, m/s"})
    LRtempCL: Optional[float] = field(default=None, metadata={"desc": "LR tire left carcass temperature, C"})
    LRtempCM: Optional[float] = field(default=None, metadata={"desc": "LR tire middle carcass temperature, C"})
    LRtempCR: Optional[float] = field(default=None, metadata={"desc": "LR tire right carcass temperature, C"})
    LRTiresAvailable: Optional[int] = field(default=None, metadata={"desc": "How many left rear tires are remaining  255 is unlimited"})
    LRTiresUsed: Optional[int] = field(default=None, metadata={"desc": "How many left rear tires used so far"})
    LRwearL: Optional[float] = field(default=None, metadata={"desc": "LR tire left percent tread remaining, %"})
    LRwearM: Optional[float] = field(default=None, metadata={"desc": "LR tire middle percent tread remaining, %"})
    LRwearR: Optional[float] = field(default=None, metadata={"desc": "LR tire right percent tread remaining, %"})
    ManifoldPress: Optional[float] = field(default=None, metadata={"desc": "Engine manifold pressure, bar"})
    ManualBoost: Optional[bool] = field(default=None, metadata={"desc": "Hybrid manual boost state"})
    ManualNoBoost: Optional[bool] = field(default=None, metadata={"desc": "Hybrid manual no boost state"})
    MemPageFaultSec: Optional[int] = field(default=None, metadata={"desc": "Memory page faults per second"})
    MemSoftPageFaultSec: Optional[int] = field(default=None, metadata={"desc": "Memory soft page faults per second"})
    OilLevel: Optional[float] = field(default=None, metadata={"desc": "Engine oil level, l"})
    OilPress: Optional[float] = field(default=None, metadata={"desc": "Engine oil pressure, bar"})
    OilTemp: Optional[float] = field(default=None, metadata={"desc": "Engine oil temperature, C"})
    OkToReloadTextures: Optional[bool] = field(default=None, metadata={"desc": "True if it is ok to reload car textures at this time"})
    OnPitRoad: Optional[bool] = field(default=None, metadata={"desc": "Is the player car on pit road between the cones"})
    P2P_Count: Optional[int] = field(default=None, metadata={"desc": "Push2Pass count of usage (or remaining in Race) on your car"})
    P2P_Status: Optional[bool] = field(default=None, metadata={"desc": "Push2Pass active or not on your car"})
    PaceMode: Optional[int] = field(default=None, metadata={"desc": "Are we pacing or not, irsdk_PaceMode"})
    Pitch: Optional[float] = field(default=None, metadata={"desc": "Pitch orientation, rad"})
    PitchRate: Optional[float] = field(default=None, metadata={"desc": "Pitch rate, rad/s"})
    PitchRate_ST: Optional[float] = field(default=None, metadata={"desc": "Pitch rate at 360 Hz, rad/s"})
    PitOptRepairLeft: Optional[float] = field(default=None, metadata={"desc": "Time left for optional repairs if repairs are active, s"})
    PitRepairLeft: Optional[float] = field(default=None, metadata={"desc": "Time left for mandatory pit repairs if repairs are active, s"})
    PitsOpen: Optional[bool] = field(default=None, metadata={"desc": "True if pit stop is allowed for the current player"})
    PitstopActive: Optional[bool] = field(default=None, metadata={"desc": "Is the player getting pit stop service"})
    PitSvFlags: Optional[int] = field(default=None, metadata={"desc": "Bitfield of pit service checkboxes, irsdk_PitSvFlags"})
    PitSvFuel: Optional[float] = field(default=None, metadata={"desc": "Pit service fuel add amount, l or kWh"})
    PitSvLFP: Optional[float] = field(default=None, metadata={"desc": "Pit service left front tire pressure, kPa"})
    PitSvLRP: Optional[float] = field(default=None, metadata={"desc": "Pit service left rear tire pressure, kPa"})
    PitSvRFP: Optional[float] = field(default=None, metadata={"desc": "Pit service right front tire pressure, kPa"})
    PitSvRRP: Optional[float] = field(default=None, metadata={"desc": "Pit service right rear tire pressure, kPa"})
    PitSvTireCompound: Optional[str] = field(default=None, metadata={"desc": "Pit service pending tire compound"})
    PlayerCarClass: Optional[int] = field(default=None, metadata={"desc": "Player car class id"})
    PlayerCarClassPosition: Optional[int] = field(default=None, metadata={"desc": "Players class position in race"})
    PlayerCarDriverIncidentCount: Optional[int] = field(default=None, metadata={"desc": "Teams current drivers incident count for this session"})
    PlayerCarDryTireSetLimit: Optional[int] = field(default=None, metadata={"desc": "Players dry tire set limit"})
    PlayerCarIdx: Optional[int] = field(default=None, metadata={"desc": "Players carIdx"})
    PlayerCarInPitStall: Optional[bool] = field(default=None, metadata={"desc": "Players car is properly in their pitstall"})
    PlayerCarMyIncidentCount: Optional[int] = field(default=None, metadata={"desc": "Players own incident count for this session"})
    PlayerCarPitSvStatus: Optional[int] = field(default=None, metadata={"desc": "Players car pit service status bits, irsdk_PitSvStatus"})
    PlayerCarPosition: Optional[int] = field(default=None, metadata={"desc": "Players position in race"})
    PlayerCarPowerAdjust: Optional[float] = field(default=None, metadata={"desc": "Players power adjust, %"})
    PlayerCarSLBlinkRPM: Optional[float] = field(default=None, metadata={"desc": "Shift light blink rpm, revs/min"})
    PlayerCarSLFirstRPM: Optional[float] = field(default=None, metadata={"desc": "Shift light first light rpm, revs/min"})
    PlayerCarSLLastRPM: Optional[float] = field(default=None, metadata={"desc": "Shift light last light rpm, revs/min"})
    PlayerCarSLShiftRPM: Optional[float] = field(default=None, metadata={"desc": "Shift light shift rpm, revs/min"})
    PlayerCarTeamIncidentCount: Optional[int] = field(default=None, metadata={"desc": "Players team incident count for this session"})
    PlayerCarTowTime: Optional[float] = field(default=None, metadata={"desc": "Players car is being towed if time is greater than zero, s"})
    PlayerCarWeightPenalty: Optional[float] = field(default=None, metadata={"desc": "Players weight penalty, kg"})
    PlayerFastRepairsUsed: Optional[int] = field(default=None, metadata={"desc": "Players car number of fast repairs used"})
    PlayerTireCompound: Optional[str] = field(default=None, metadata={"desc": "Players car current tire compound"})
    PlayerTrackSurface: Optional[int] = field(default=None, metadata={"desc": "Players car track surface type, irsdk_TrkLoc"})
    PlayerTrackSurfaceMaterial: Optional[int] = field(default=None, metadata={"desc": "Players car track surface material type, irsdk_TrkSurf"})
    Precipitation: Optional[float] = field(default=None, metadata={"desc": "Precipitation at start/finish line, %"})
    PushToPass: Optional[bool] = field(default=None, metadata={"desc": "Push to pass button state"})
    PushToTalk: Optional[bool] = field(default=None, metadata={"desc": "Push to talk button state"})
    RaceLaps: Optional[int] = field(default=None, metadata={"desc": "Laps completed in race"})
    RadioTransmitCarIdx: Optional[int] = field(default=None, metadata={"desc": "The car index of the current person speaking on the radio"})
    RadioTransmitFrequencyIdx: Optional[int] = field(default=None, metadata={"desc": "The frequency index of the current person speaking on the radio"})
    RadioTransmitRadioIdx: Optional[int] = field(default=None, metadata={"desc": "The radio index of the current person speaking on the radio"})
    RearTireSetsAvailable: Optional[int] = field(default=None, metadata={"desc": "How many rear tire sets are remaining  255 is unlimited"})
    RearTireSetsUsed: Optional[int] = field(default=None, metadata={"desc": "How many rear tire sets used so far"})
    RelativeHumidity: Optional[float] = field(default=None, metadata={"desc": "Relative Humidity at start/finish line, %"})
    ReplayFrameNum: Optional[int] = field(default=None, metadata={"desc": "Integer replay frame number (60 per second)"})
    ReplayFrameNumEnd: Optional[int] = field(default=None, metadata={"desc": "Integer replay frame number from end of tape"})
    ReplayPlaySlowMotion: Optional[bool] = field(default=None, metadata={"desc": "0=not slow motion  1=replay is in slow motion"})
    ReplayPlaySpeed: Optional[float] = field(default=None, metadata={"desc": "Replay playback speed"})
    ReplaySessionNum: Optional[int] = field(default=None, metadata={"desc": "Replay session number"})
    ReplaySessionTime: Optional[float] = field(default=None, metadata={"desc": "Seconds since replay session start, s"})
    RFbrakeLinePress: Optional[float] = field(default=None, metadata={"desc": "RF brake line pressure, bar"})
    RFcoldPressure: Optional[float] = field(default=None, metadata={"desc": "RF tire cold pressure  as set in the garage, kPa"})
    RFshockDefl: Optional[float] = field(default=None, metadata={"desc": "RF shock deflection, m"})
    RFshockDefl_ST: Optional[float] = field(default=None, metadata={"desc": "RF shock deflection at 360 Hz, m"})
    RFshockVel: Optional[float] = field(default=None, metadata={"desc": "RF shock velocity, m/s"})
    RFshockVel_ST: Optional[float] = field(default=None, metadata={"desc": "RF shock velocity at 360 Hz, m/s"})
    RFtempCL: Optional[float] = field(default=None, metadata={"desc": "RF tire left carcass temperature, C"})
    RFtempCM: Optional[float] = field(default=None, metadata={"desc": "RF tire middle carcass temperature, C"})
    RFtempCR: Optional[float] = field(default=None, metadata={"desc": "RF tire right carcass temperature, C"})
    RFTiresAvailable: Optional[int] = field(default=None, metadata={"desc": "How many right front tires are remaining  255 is unlimited"})
    RFTiresUsed: Optional[int] = field(default=None, metadata={"desc": "How many right front tires used so far"})
    RFwearL: Optional[float] = field(default=None, metadata={"desc": "RF tire left percent tread remaining, %"})
    RFwearM: Optional[float] = field(default=None, metadata={"desc": "RF tire middle percent tread remaining, %"})
    RFwearR: Optional[float] = field(default=None, metadata={"desc": "RF tire right percent tread remaining, %"})
    RightTireSetsAvailable: Optional[int] = field(default=None, metadata={"desc": "How many right tire sets are remaining  255 is unlimited"})
    RightTireSetsUsed: Optional[int] = field(default=None, metadata={"desc": "How many right tire sets used so far"})
    Roll: Optional[float] = field(default=None, metadata={"desc": "Roll orientation, rad"})
    RollRate: Optional[float] = field(default=None, metadata={"desc": "Roll rate, rad/s"})
    RollRate_ST: Optional[float] = field(default=None, metadata={"desc": "Roll rate at 360 Hz, rad/s"})
    RPM: Optional[float] = field(default=None, metadata={"desc": "Engine rpm, revs/min"})
    RRbrakeLinePress: Optional[float] = field(default=None, metadata={"desc": "RR brake line pressure, bar"})
    RRcoldPressure: Optional[float] = field(default=None, metadata={"desc": "RR tire cold pressure  as set in the garage, kPa"})
    RRshockDefl: Optional[float] = field(default=None, metadata={"desc": "RR shock deflection, m"})
    RRshockDefl_ST: Optional[float] = field(default=None, metadata={"desc": "RR shock deflection at 360 Hz, m"})
    RRshockVel: Optional[float] = field(default=None, metadata={"desc": "RR shock velocity, m/s"})
    RRshockVel_ST: Optional[float] = field(default=None, metadata={"desc": "RR shock velocity at 360 Hz, m/s"})
    RRtempCL: Optional[float] = field(default=None, metadata={"desc": "RR tire left carcass temperature, C"})
    RRtempCM: Optional[float] = field(default=None, metadata={"desc": "RR tire middle carcass temperature, C"})
    RRtempCR: Optional[float] = field(default=None, metadata={"desc": "RR tire right carcass temperature, C"})
    RRTiresAvailable: Optional[int] = field(default=None, metadata={"desc": "How many right rear tires are remaining  255 is unlimited"})
    RRTiresUsed: Optional[int] = field(default=None, metadata={"desc": "How many right rear tires used so far"})
    RRwearL: Optional[float] = field(default=None, metadata={"desc": "RR tire left percent tread remaining, %"})
    RRwearM: Optional[float] = field(default=None, metadata={"desc": "RR tire middle percent tread remaining, %"})
    RRwearR: Optional[float] = field(default=None, metadata={"desc": "RR tire right percent tread remaining, %"})
    SessionFlags: Optional[int] = field(default=None, metadata={"desc": "Session flags, irsdk_Flags"})
    SessionJokerLapsRemain: Optional[int] = field(default=None, metadata={"desc": "Joker laps remaining to be taken"})
    SessionLapsRemain: Optional[int] = field(default=None, metadata={"desc": "Old laps left till session ends use SessionLapsRemainEx"})
    SessionLapsRemainEx: Optional[int] = field(default=None, metadata={"desc": "New improved laps left till session ends"})
    SessionLapsTotal: Optional[int] = field(default=None, metadata={"desc": "Total number of laps in session"})
    SessionNum: Optional[int] = field(default=None, metadata={"desc": "Session number"})
    SessionOnJokerLap: Optional[bool] = field(default=None, metadata={"desc": "Player is currently completing a joker lap"})
    SessionState: Optional[int] = field(default=None, metadata={"desc": "Session state, irsdk_SessionState"})
    SessionTick: Optional[int] = field(default=None, metadata={"desc": "Current update number"})
    SessionTime: Optional[float] = field(default=None, metadata={"desc": "Seconds since session start, s"})
    SessionTimeOfDay: Optional[float] = field(default=None, metadata={"desc": "Time of day in seconds, s"})
    SessionTimeRemain: Optional[float] = field(default=None, metadata={"desc": "Seconds left till session ends, s"})
    SessionTimeTotal: Optional[float] = field(default=None, metadata={"desc": "Total number of seconds in session, s"})
    SessionUniqueID: Optional[str] = field(default=None, metadata={"desc": "Session ID"})
    ShiftGrindRPM: Optional[float] = field(default=None, metadata={"desc": "RPM of shifter grinding noise, RPM"})
    ShiftIndicatorPct: Optional[float] = field(default=None, metadata={"desc": "DEPRECATED use DriverCarSLBlinkRPM instead, %"})
    ShiftPowerPct: Optional[float] = field(default=None, metadata={"desc": "Friction torque applied to gears when shifting or grinding, %"})
    Skies: Optional[int] = field(default=None, metadata={"desc": "Skies (0=clear/1=p cloudy/2=m cloudy/3=overcast)"})
    SolarAltitude: Optional[float] = field(default=None, metadata={"desc": "Sun angle above horizon in radians, rad"})
    SolarAzimuth: Optional[float] = field(default=None, metadata={"desc": "Sun angle clockwise from north in radians, rad"})
    Speed: Optional[float] = field(default=None, metadata={"desc": "GPS vehicle speed, m/s"})
    SteeringFFBEnabled: Optional[bool] = field(default=None, metadata={"desc": "Force feedback is enabled"})
    SteeringWheelAngle: Optional[float] = field(default=None, metadata={"desc": "Steering wheel angle, rad"})
    SteeringWheelAngleMax: Optional[float] = field(default=None, metadata={"desc": "Steering wheel max angle, rad"})
    SteeringWheelLimiter: Optional[float] = field(default=None, metadata={"desc": "Force feedback limiter strength limits impacts and oscillation, %"})
    SteeringWheelMaxForceNm: Optional[float] = field(default=None, metadata={"desc": "Value of strength or max force slider in Nm for FFB, N*m"})
    SteeringWheelPctDamper: Optional[float] = field(default=None, metadata={"desc": "Force feedback % max damping, %"})
    SteeringWheelPctIntensity: Optional[float] = field(default=None, metadata={"desc": "Force feedback % max intensity, %"})
    SteeringWheelPctSmoothing: Optional[float] = field(default=None, metadata={"desc": "Force feedback % max smoothing, %"})
    SteeringWheelPctTorque: Optional[float] = field(default=None, metadata={"desc": "Force feedback % max torque on steering shaft unsigned, %"})
    SteeringWheelPctTorqueSign: Optional[float] = field(default=None, metadata={"desc": "Force feedback % max torque on steering shaft signed, %"})
    SteeringWheelPctTorqueSignStops: Optional[float] = field(default=None, metadata={"desc": "Force feedback % max torque on steering shaft signed stops, %"})
    SteeringWheelPeakForceNm: Optional[float] = field(default=None, metadata={"desc": "Peak torque mapping to direct input units for FFB, N*m"})
    SteeringWheelTorque: Optional[float] = field(default=None, metadata={"desc": "Output torque on steering shaft, N*m"})
    SteeringWheelTorque_ST: Optional[float] = field(default=None, metadata={"desc": "Output torque on steering shaft at 360 Hz, N*m"})
    SteeringWheelUseLinear: Optional[bool] = field(default=None, metadata={"desc": "True if steering wheel force is using linear mode"})
    Throttle: Optional[float] = field(default=None, metadata={"desc": "0=off throttle to 1=full throttle, %"})
    ThrottleRaw: Optional[float] = field(default=None, metadata={"desc": "Raw throttle input 0=off throttle to 1=full throttle, %"})
    TireLF_RumblePitch: Optional[float] = field(default=None, metadata={"desc": "Players LF Tire Sound rumblestrip pitch, Hz"})
    TireLR_RumblePitch: Optional[float] = field(default=None, metadata={"desc": "Players LR Tire Sound rumblestrip pitch, Hz"})
    TireRF_RumblePitch: Optional[float] = field(default=None, metadata={"desc": "Players RF Tire Sound rumblestrip pitch, Hz"})
    TireRR_RumblePitch: Optional[float] = field(default=None, metadata={"desc": "Players RR Tire Sound rumblestrip pitch, Hz"})
    TireSetsAvailable: Optional[int] = field(default=None, metadata={"desc": "How many tire sets are remaining  255 is unlimited"})
    TireSetsUsed: Optional[int] = field(default=None, metadata={"desc": "How many tire sets used so far"})
    TrackTemp: Optional[float] = field(default=None, metadata={"desc": "Deprecated  set to TrackTempCrew, C"})
    TrackTempCrew: Optional[float] = field(default=None, metadata={"desc": "Temperature of track measured by crew around track, C"})
    TrackWetness: Optional[int] = field(default=None, metadata={"desc": "How wet is the average track surface, irsdk_TrackWetness"})
    VelocityX: Optional[float] = field(default=None, metadata={"desc": "X velocity, m/s"})
    VelocityX_ST: Optional[float] = field(default=None, metadata={"desc": "X velocity, m/s at 360 Hz"})
    VelocityY: Optional[float] = field(default=None, metadata={"desc": "Y velocity, m/s"})
    VelocityY_ST: Optional[float] = field(default=None, metadata={"desc": "Y velocity, m/s at 360 Hz"})
    VelocityZ: Optional[float] = field(default=None, metadata={"desc": "Z velocity, m/s"})
    VelocityZ_ST: Optional[float] = field(default=None, metadata={"desc": "Z velocity, m/s at 360 Hz"})
    VertAccel: Optional[float] = field(default=None, metadata={"desc": "Vertical acceleration (including gravity), m/s^2"})
    VertAccel_ST: Optional[float] = field(default=None, metadata={"desc": "Vertical acceleration (including gravity) at 360 Hz, m/s^2"})
    VidCapActive: Optional[bool] = field(default=None, metadata={"desc": "True if video currently being captured"})
    VidCapEnabled: Optional[bool] = field(default=None, metadata={"desc": "True if video capture system is enabled"})
    Voltage: Optional[float] = field(default=None, metadata={"desc": "Engine voltage, V"})
    WaterLevel: Optional[float] = field(default=None, metadata={"desc": "Engine coolant level, l"})
    WaterTemp: Optional[float] = field(default=None, metadata={"desc": "Engine coolant temp, C"})
    WeatherDeclaredWet: Optional[bool] = field(default=None, metadata={"desc": "The steward says rain tires can be used"})
    WindDir: Optional[float] = field(default=None, metadata={"desc": "Wind direction at start/finish line, rad"})
    WindVel: Optional[float] = field(default=None, metadata={"desc": "Wind velocity at start/finish line, m/s"})
    Yaw: Optional[float] = field(default=None, metadata={"desc": "Yaw orientation, rad"})
    YawNorth: Optional[float] = field(default=None, metadata={"desc": "Yaw orientation relative to north, rad"})
    YawRate: Optional[float] = field(default=None, metadata={"desc": "Yaw rate, rad/s"})
    YawRate_ST: Optional[float] = field(default=None, metadata={"desc": "Yaw rate at 360 Hz, rad/s"})